- name: Deploy Calculator Container
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Pull Docker Image
      command: docker pull mt2024013/calculator

    - name: Stop existing container
      command: docker rm -f calculator_container
      ignore_errors: yes

    - name: Run the Calculator Container in Interactive Mode
      command: docker run -dit --name calculator_container mt2024013/calculator
